# Configuração de Impressoras SNMP
# Estrutura organizada por modelo de impressora

printers:
  # Impressora Brother NC-8300w
  - model: "Brother NC-8300w"
    description: "Impressora multifuncional Brother NC-8300w"
    ip: "192.168.15.106"
    community: "public"
    oids:
      paginasImpressas:
        oid: "1.3.6.1.2.1.43.10.2.1.4.1.1"
        description: "Contador de páginas impressas"
        type: "Counter32"
      modeloImpressora:
        oid: "1.3.6.1.2.1.1.1.0"
        description: "Descrição do sistema/modelo"
        type: "String"
      numeroSerie:
        oid: "1.3.6.1.2.1.43.5.1.1.17.1"
        description: "Número de série da impressora"
        type: "String"
      nomeSistema:
        oid: "1.3.6.1.2.1.1.5.0"
        description: "Nome do sistema (sysName)"
        type: "String"

  # # Exemplo de outra impressora HP (modelo de exemplo)
  # - model: "HP LaserJet Pro M404n"
  #   description: "Impressora HP LaserJet Pro M404n"
  #   ip: "192.168.15.107"
  #   community: "public"
  #   oids:
  #     paginasImpressas:
  #       oid: "1.3.6.1.2.1.43.10.2.1.4.1.1"
  #       description: "Contador de páginas impressas"
  #       type: "Counter32"
  #     modeloImpressora:
  #       oid: "1.3.6.1.2.1.1.1.0"
  #       description: "Descrição do sistema/modelo"
  #       type: "String"
  #     numeroSerie:
  #       oid: "1.3.6.1.2.1.43.5.1.1.17.1"
  #       description: "Número de série da impressora"
  #       type: "String"
  #     nomeSistema:
  #       oid: "1.3.6.1.2.1.1.5.0"
  #       description: "Nome do sistema (sysName)"
  #       type: "String"

  # # Exemplo de impressora Canon (modelo de exemplo)
  # - model: "Canon imageRUNNER"
  #   description: "Multifuncional Canon imageRUNNER"
  #   ip: "192.168.15.108"
  #   community: "public"
  #   oids:
  #     paginasImpressas:
  #       oid: "1.3.6.1.2.1.43.10.2.1.4.1.1"
  #       description: "Contador de páginas impressas"
  #       type: "Counter32"
  #     modeloImpressora:
  #       oid: "1.3.6.1.2.1.1.1.0"
  #       description: "Descrição do sistema/modelo"
  #       type: "String"
  #     numeroSerie:
  #       oid: "1.3.6.1.4.1.1602.1.2.1.4.1.1.3.1"
  #       description: "Número de série (Canon específico)"
  #       type: "String"
  #     nomeSistema:
  #       oid: "1.3.6.1.2.1.1.5.0"
  #       description: "Nome do sistema (sysName)"
  #       type: "String"

# Configuração global
config:
  timeout: 5
  retries: 2
  snmpVersion: "2c"
  defaultCommunity: "public"
